### ISSUE TITLE
Resources for Indian cities don't show up

### ISSUE THREAD

**Issue by ameyaraje** [Ultraworking/locally-informed#46]
Steps to reproduce:
1. Enter any Indian city (e.g. Mumbai or Bangalore/Bengaluru).

At this point, resources for these cities should show up. The .json files for their states have been added, but they don't appear.

**Comment by saadzafar** [comment]
Upon checking, I notice the regional resources for india have been added at a state level where they should've been added at a city level.

Due to certain constraints, states are only supported as regions for the United States, for all other countries the regions should be the names of cities.

I apologise for the confusion.

**Comment by ameyaraje** [comment]
So should we remove the states and add individual cities then? For Spain, cities have been added as regions: https://github.com/Ultraworking/locally-informed/tree/master/countries/esp/regions and this seems to work properly. 
Should this be the structure then?
I can make those changes if you want me to!

**Comment by saadzafar** [comment]
I understand there are a lot of cities within the states of Maharashtra and Karnataka and it would be extremely redundant to duplicate the state level resources for each city.

I am currently testing an update that would allow state level resources to be added for India.

Thanks for bringing this my attention. Cheers!

**Comment by saadzafar** [comment]
I'm happy to report that the State level resource feature for India has been successfully pushed.
Huzzah!
